### ISSUE TITLE
DisplayName always “anon” or “undefined”

### ISSUE THREAD

**Issue by karimK3** [ChatKitty/chatkitty-example-react-native#12]
Hi,

When i start a session the displayName of my users are always “anon” or “undefined”. Or my firebase user displayName is correct.

I tried updateCurrentUser but when i create a new channel, the correct username appear only in properties, not directly in members :

```
 [{"callStatus": "AVAILABLE", 
"displayName": "undefined", 
"displayPictureUrl": "https://api.chatkitty.com/v1/picture/undefined", 
"id": 336489, 
"isGuest": true, 
"name": "undefined", 
"presence": {"online": true, "status": "AVAILABLE"}, 
"properties": {"displayName": "Apple5", 
"expo-push-token": "ExponentPushToken[h6TTB1PyUSt_eHSz5KW3r5]"}, 
"type": "PERSON"}, 
{"displayName": "anon", 
"displayPictureUrl": "https://api.chatkitty.com/v1/picture/anon", 
"id": 336993, 
"name": "9bTR7Acme1MgwgrBOm8dy6P00Pf1", 
"presence": {"online": false, "status": "UNAVAILABLE"}, 
"properties": {"displayName": "Zooooo"}, 
"type": "PERSON"}]
```

**Comment by aerovulpe** [comment]
Hey @karimK3, how are you passing`displayName` in your Chat Function?

Also, updating the current user display name should look like this.

```js
await chatkitty.updateCurrentUser((user) => {
  // Update display name
  user.displayName = '...';

  return user; // Return updated user
});
```

**Comment by karimK3** [comment]
Hey @aerovulpe 

When I launch my app I do this : 

```
 const result = chatkitty.startSession({
      username: user.uid,
      displayName: user.name,
      authParams: {
        idToken: await user.getIdToken()
      }
    });
```


And the result is : 

```
NoActiveSessionError {
  "error": "NoActiveSessionError",
  "message": "You're not connected to ChatKitty.",
}
```
My users displayName are always "anon". What does it mean ? 

Because I can still call createChannel, listChannels and it works correctly. 
I can talk in a channel, but every users are always "anon" and therefore no avatars.

I tried updateCurrentUser just like in your exemple but no results. 

Thank you for your help

**Comment by aerovulpe** [comment]
The `anon` must be coming from your "User Attempted Start Session" Chat Function (the ChatKitty service doesn't define or use `anon` anywhere in its codebase). You can check the chat function invocation logs on the dashboard (https://dashboard.chatkitty.com/) and update your "User Attempted Start Session" Chat Function accordingly.

**Comment by karimK3** [comment]
It works, the problem was from the` idToken` and the `anon` was effectively from the "User Attempted Start Session".
Thanks !

**Comment by karimK3** [comment]
It works, the problem was from the `idToken` and the `anon` was effectively from the "User Attempted Start Session".
Thanks !
