### ISSUE TITLE
Module parse failed: Unexpected token (117:6) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by UnknownCrafts** [ChatKitty/chatkitty-example-react-native#3]
<img width="1440" alt="Screen Shot 2021-01-13 at 12 03 25 PM" src="https://user-images.githubusercontent.com/65975222/104484600-74a00980-5597-11eb-80c6-ffe64ffaa051.png">

Idk what to do, I checked the place with the error but the file itself doesn't show any errors.

<img width="1440" alt="Screen Shot 2021-01-13 at 12 05 31 PM" src="https://user-images.githubusercontent.com/65975222/104484756-a87b2f00-5597-11eb-94d0-a613fc402ca1.png">

**Comment by UnknownCrafts** [comment]
Can anyone help with this?

**Comment by aerovulpe** [comment]
Hey @FakeZombieCraft Are you running in the notification demo  targeting web? The `react-native-in-app-notification` library expects a React Native environment and currently only works when targeting Android or iOS.

**Comment by aerovulpe** [comment]
I also found an issue with Expo where it doesn't compile external packages with JSX. I solved it after stumbling upon this thread https://github.com/expo/expo/issues/6157. And I've updated the tutorial code to handle it.

I've also updated our fork of the `react-native-in-app-notification` to support running on web. If you checkout the latest commit, you should no longer see this issue.
