### ISSUE TITLE
How do I add an option to make private chats/delete chatrooms(Feature idea)

### ISSUE THREAD

**Issue by UnknownCrafts** [ChatKitty/chatkitty-example-react-native#5]
This feature could work by providing an email of the person that someone wants to talk with, and then after adding the email address it could be possible to chat with them privately without anyone else seeing the chatroom. This simple concept can be further enhanced by allowing users to make private chatrooms with multiple users. There could also be an option to leave the chatroom(non-admins) and admins/creators of the chatrooms could delete the chatroom.

I am not sure if this idea was already planned... if it wasn't then I hope this helps.

Also, I am liking the chat app project. keep up the good work.

**Comment by aerovulpe** [comment]
Thanks @FakeZombieCraft! 😃

Yeah, direct messaging is an important feature and ChatKitty supports it. You can create a direct channel to chat privately with up to 10 users like this:

```javascript
let result = await kitty.createChannel({
  type: 'DIRECT',
  name: channelName,
  members: [{ id: member1Id }, { id: member2Id }],
});
```

Here's some documentation on creating different channel types 
https://chatkitty.github.io/chatkitty-js/classes/_lib_model_channel_create_.createchannelrequest.html

I'm also planning to write an article on how to implement direct chat using direct channels and I'll update this project with that code.

About leaving a channel (chatroom), the backend support is already there so I can quickly add the client SDK feature. If you want to remove a chat member as an admin, you can use the Platform API

https://docs.chatkitty.com/platform/v1/

**Comment by aerovulpe** [comment]
@FakeZombieCraft I've written a new blog post covering direct messaging and leaving a channel.

https://www.chatkitty.com/blog/posts/building-a-chat-app-with-react-native-and-gifted-chat-part-4/

Hope this helps. :)
