### ISSUE TITLE
Anyway to fix this issue? (small issue)

### ISSUE THREAD

**Issue by UnknownCrafts** [ChatKitty/chatkitty-example-react-native#6]
<img width="1440" alt="Screen Shot 2021-01-14 at 8 38 54 AM" src="https://user-images.githubusercontent.com/65975222/104598004-0b2a0480-5644-11eb-8a1b-5bf3326a99b1.png">
it says that the wrong versions are installed, I just want to know what package I need to upgrade to make the warning go away. Otherwise, this issue doesn't really interfere or break anything, but it would be good to not take any chances.

**Comment by UnknownCrafts** [comment]
I know it says to downgrade, but I want to know what I can upgrade if possible.

**Comment by aerovulpe** [comment]
Done 👍
